M48
; DRILL file {KiCad 9.0.6} date 2025-12-05T19:36:25+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-05T19:36:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.950
%
G90
G05
T1
X105.9Y-60.13
X105.9Y-65.91
T2
X101.15Y-73.2
X101.15Y-75.5
M30
